// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CountryResponse } from './country-response';

/**
 *
 * @export
 * @interface Address
 */
export interface Address {
    /**
     *
     * @type {string}
     * @memberof Address
     */
    phone?: string;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    email?: string;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    firstname?: string;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    lastname?: string;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    address?: string;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    address_two?: string;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    address_three?: string;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    city?: string;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    state?: string;
    /**
     *
     * @type {CountryResponse}
     * @memberof Address
     */
    country?: CountryResponse;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    postal_code?: string;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    salutation?: string;
    /**
     *
     * @type {boolean}
     * @memberof Address
     */
    _default?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof Address
     */
    shipping?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof Address
     */
    delivery?: boolean;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    delivery_instructions?: string;
    /**
     *
     * @type {object | Array<object>}
     * @memberof Address
     */
    meta?: object | Array<object>;
    /**
     *
     * @type {string}
     * @memberof Address
     */
    last_used_at?: string;
}


