// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface BlogUpdateBody
 */
export interface BlogUpdateBody {
    /**
     *
     * @type {object}
     * @memberof BlogUpdateBody
     */
    attribute_data?: object;
    /**
     *
     * @type {string}
     * @memberof BlogUpdateBody
     */
    family_id?: string;
}


