// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AssociationGroupCollectionAllOf1 } from './association-group-collection-all-of1';
import { Category } from './category';
import { CategoryCollectionAllOf } from './category-collection-all-of';
import { Pagination } from './pagination';

/**
 * @type CategoryCollection
 * @export
 */
export type CategoryCollection = AssociationGroupCollectionAllOf1 & CategoryCollectionAllOf;



