// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ShippingShippingMethodIdName } from './shipping-shipping-method-id-name';

/**
 *
 * @export
 * @interface CreateCategoryBody
 */
export interface CreateCategoryBody {
    /**
     *
     * @type {string}
     * @memberof CreateCategoryBody
     */
    url: string;
    /**
     *
     * @type {string}
     * @memberof CreateCategoryBody
     */
    path: string;
    /**
     *
     * @type {ShippingShippingMethodIdName}
     * @memberof CreateCategoryBody
     */
    name: ShippingShippingMethodIdName;
}


