// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface CreateCustomerGroupBody
 */
export interface CreateCustomerGroupBody {
    /**
     *
     * @type {string}
     * @memberof CreateCustomerGroupBody
     */
    handle?: string;
    /**
     *
     * @type {string}
     * @memberof CreateCustomerGroupBody
     */
    name?: string;
    /**
     *
     * @type {boolean}
     * @memberof CreateCustomerGroupBody
     */
    _default?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof CreateCustomerGroupBody
     */
    system?: boolean | null;
}


