// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AssociationGroupCollectionAllOf1 } from './association-group-collection-all-of1';
import { Discount } from './discount';
import { DiscountCollectionAllOf } from './discount-collection-all-of';
import { Pagination } from './pagination';

/**
 * @type DiscountCollection
 * @export
 */
export type DiscountCollection = AssociationGroupCollectionAllOf1 & DiscountCollectionAllOf;



