// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DiscountsDiscountIdRewardsDataProducts } from './discounts-discount-id-rewards-data-products';

/**
 *
 * @export
 * @interface DiscountsDiscountIdRewardsData
 */
export interface DiscountsDiscountIdRewardsData {
    /**
     *
     * @type {Array<DiscountsDiscountIdRewardsDataProducts>}
     * @memberof DiscountsDiscountIdRewardsData
     */
    products?: Array<DiscountsDiscountIdRewardsDataProducts>;
}


