// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DiscountsDiscountIdSetsData } from './discounts-discount-id-sets-data';

/**
 *
 * @export
 * @interface DiscountsDiscountIdSets
 */
export interface DiscountsDiscountIdSets {
    /**
     *
     * @type {Array<DiscountsDiscountIdSetsData>}
     * @memberof DiscountsDiscountIdSets
     */
    data?: Array<DiscountsDiscountIdSetsData>;
}


