// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DiscountsDiscountIdChannelsData } from './discounts-discount-id-channels-data';

/**
 *
 * @export
 * @interface DiscountsDiscountIdChannels
 */
export interface DiscountsDiscountIdChannels {
    /**
     *
     * @type {DiscountsDiscountIdChannelsData}
     * @memberof DiscountsDiscountIdChannels
     */
    data?: DiscountsDiscountIdChannelsData;
}


