// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface InlineObject22
 */
export interface InlineObject22 {
    /**
     * Array of category ID\'s
     * @type {Array<string>}
     * @memberof InlineObject22
     */
    categories: Array<string>;
}


