// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface InlineResponse4222
 */
export interface InlineResponse4222 {
    /**
     *
     * @type {Array<string>}
     * @memberof InlineResponse4222
     */
    id?: Array<string>;
}


