// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface InlineObject2
 */
export interface InlineObject2 {
    /**
     * Pass all products you wish to be associated.
     * @type {Array<string>}
     * @memberof InlineObject2
     */
    products?: Array<string>;
}


