// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     *
     * @type {string}
     * @memberof InlineResponse2004
     */
    date?: string;
    /**
     *
     * @type {string}
     * @memberof InlineResponse2004
     */
    sub_total?: string;
    /**
     *
     * @type {string}
     * @memberof InlineResponse2004
     */
    delivery_total?: string;
    /**
     *
     * @type {string}
     * @memberof InlineResponse2004
     */
    tax_total?: string;
    /**
     *
     * @type {string}
     * @memberof InlineResponse2004
     */
    order_total?: string;
    /**
     *
     * @type {string}
     * @memberof InlineResponse2004
     */
    discount_total?: string;
}


