// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface InlineObject13
 */
export interface InlineObject13 {
    /**
     * If left blank, the full amount will be refunded
     * @type {number}
     * @memberof InlineObject13
     */
    amount?: number;
    /**
     *
     * @type {string}
     * @memberof InlineObject13
     */
    notes?: string;
}


