// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface Layout
 */
export interface Layout {
    /**
     *
     * @type {string}
     * @memberof Layout
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Layout
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Layout
     */
    handle: string;
    /**
     *
     * @type {string}
     * @memberof Layout
     */
    type: string;
}


