// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface Links
 */
export interface Links {
    /**
     *
     * @type {string}
     * @memberof Links
     */
    first?: string;
    /**
     *
     * @type {string}
     * @memberof Links
     */
    last?: string;
    /**
     *
     * @type {string}
     * @memberof Links
     */
    prev?: string | null;
    /**
     *
     * @type {string}
     * @memberof Links
     */
    next?: string | null;
}


