// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface OrderLine
 */
export interface OrderLine {
    /**
     *
     * @type {string}
     * @memberof OrderLine
     */
    id?: string;
    /**
     *
     * @type {number}
     * @memberof OrderLine
     */
    quantity?: number;
    /**
     *
     * @type {number}
     * @memberof OrderLine
     */
    line_total?: number;
    /**
     *
     * @type {number}
     * @memberof OrderLine
     */
    discount_total?: number;
    /**
     *
     * @type {number}
     * @memberof OrderLine
     */
    delivery_total?: number;
    /**
     *
     * @type {number}
     * @memberof OrderLine
     */
    unit_price?: number;
    /**
     *
     * @type {number}
     * @memberof OrderLine
     */
    unit_qty?: number;
    /**
     *
     * @type {number}
     * @memberof OrderLine
     */
    tax_total?: number;
    /**
     *
     * @type {number}
     * @memberof OrderLine
     */
    tax_rate?: number;
    /**
     *
     * @type {string}
     * @memberof OrderLine
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof OrderLine
     */
    option?: string;
    /**
     *
     * @type {string}
     * @memberof OrderLine
     */
    sku?: string;
    /**
     *
     * @type {boolean}
     * @memberof OrderLine
     */
    is_shipping?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof OrderLine
     */
    is_manual?: boolean;
    /**
     *
     * @type {object}
     * @memberof OrderLine
     */
    meta?: object;
}


