// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OrderType } from './order-type';

/**
 *
 * @export
 * @interface OrderTypeCollection
 */
export interface OrderTypeCollection {
    /**
     *
     * @type {Array<OrderType>}
     * @memberof OrderTypeCollection
     */
    data?: Array<OrderType>;
}


