// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomerPrice } from './customer-price';

/**
 *
 * @export
 * @interface ProductVariantCustomerPricing
 */
export interface ProductVariantCustomerPricing {
    /**
     *
     * @type {Array<CustomerPrice>}
     * @memberof ProductVariantCustomerPricing
     */
    data?: Array<CustomerPrice>;
}


