// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface ReorderCategoryBody
 */
export interface ReorderCategoryBody {
    /**
     * before, after, over
     * @type {string}
     * @memberof ReorderCategoryBody
     */
    action?: string;
    /**
     * The ID of the category which moved
     * @type {string}
     * @memberof ReorderCategoryBody
     */
    moved_node: string;
    /**
     * The id of the category affected
     * @type {string}
     * @memberof ReorderCategoryBody
     */
    node: string;
}


