// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AssociationGroupCollectionAllOf1 } from './association-group-collection-all-of1';
import { Pagination } from './pagination';
import { Route } from './route';
import { RouteCollectionAllOf } from './route-collection-all-of';

/**
 * @type RouteCollection
 *
 * @export
 */
export type RouteCollection = AssociationGroupCollectionAllOf1 & RouteCollectionAllOf;



