// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface SavedSearch
 */
export interface SavedSearch {
    /**
     *
     * @type {string}
     * @memberof SavedSearch
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof SavedSearch
     */
    name?: string;
    /**
     *
     * @type {object}
     * @memberof SavedSearch
     */
    payload?: object;
}


