// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SavedSearch } from './saved-search';

/**
 *
 * @export
 * @interface SavedSearchResponse
 */
export interface SavedSearchResponse {
    /**
     *
     * @type {SavedSearch}
     * @memberof SavedSearchResponse
     */
    data?: SavedSearch;
}


