// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Links } from './links';
import { Pagination } from './pagination';
import { Search } from './search';

/**
 *
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     *
     * @type {Array<Search>}
     * @memberof SearchResponse
     */
    data?: Array<Search>;
    /**
     *
     * @type {Pagination & object}
     * @memberof SearchResponse
     */
    meta?: Pagination & object;
    /**
     *
     * @type {Links}
     * @memberof SearchResponse
     */
    links?: Links;
}


