// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AttributeData } from './attribute-data';
import { LocalisedAttributeData } from './localised-attribute-data';
import { ShippingMethodAllOf } from './shipping-method-all-of';

/**
 * @type ShippingMethod
 * @export
 */
export type ShippingMethod = AttributeData & LocalisedAttributeData & ShippingMethodAllOf;



