// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Tag } from './tag';

/**
 *
 * @export
 * @interface TagResponse
 */
export interface TagResponse {
    /**
     *
     * @type {Tag}
     * @memberof TagResponse
     */
    data?: Tag;
}


