// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 0.12.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AssociationGroupCollectionAllOf1 } from './association-group-collection-all-of1';
import { Pagination } from './pagination';
import { Tax } from './tax';
import { TaxCollectionAllOf } from './tax-collection-all-of';

/**
 * @type TaxCollection
 * @export
 */
export type TaxCollection = AssociationGroupCollectionAllOf1 & TaxCollectionAllOf;



